### ISSUE TITLE
Error detected while processing function vundle#installer#new

### ISSUE THREAD

**Issue by nscott32** [VundleVim/Vundle.vim#690]
Hello,

after reading several issues about similar problems I couldn't get rid off errors, even with minimal settings recommended in another issue. I have move vim folder and vimrc to other places and running this vimrc :
```
set nocompatible
set shell=/bin/bash
syntax on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on

```
After calling `:PluginInstall` or `:BundleUpdate`                                    
```
Error detected while processing function vundle#installer#new:
line    6:
E121: Undefined variable: g:vundle#bundles
E116: Invalid arguments for function copy(g:vundle#bundles), 'index(a:000, v:val
.name) > -1')
E116: Invalid arguments for function filter(copy(g:vundle#bundles), 'index(a:000
, v:val.name) > -1')
E15: Invalid expression: filter(copy(g:vundle#bundles), 'index(a:000, v:val.name
) > -1')
```

Problem has been solve in some issues adding setting bash as vim's shell, but that's not the case for me.

**Comment by nfischer** [comment]
```
# These commands should all succeed
$ cd ~/.vim/bundle
$ rm -rf Vundle.vim/
$ git clone https://github.com/VundleVim/Vundle.vim.git
```

@nscott32 what shell are you using? What OS are you using?

**Comment by nscott32** [comment]
I still get the same error. I run vim on updated Archlinux using zsh in termite.

**Comment by wsdjeg** [comment]
how about this command 
```shell
mv ~/.vimrc ~/.vimrc_back
mv ~/.vim ~/.vim_back
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp ~/.vim/bundle/Vundle.vim/test/minirc.vim ~/.vimrc
```

**Comment by nscott32** [comment]
Sorry, it doesn't solve the problem, after `PluginUpdate` or `BundleUpdate` error is still the same, even after `set shell=/bin/bash`.

**Comment by wsdjeg** [comment]
are you using `root` user?

**Comment by nscott32** [comment]
No I use another user and I need sudo for root's commands.

**Comment by VeryCB** [comment]
I have the same issue in Ubuntu precise (12.04.2 LTS)

**Comment by VeryCB** [comment]
error message after enter `:PluginInstall`:
```
Error detected while processing function vundle#installer#new:
line   13:
No bundles were selected for operation
```

**Comment by VeryCB** [comment]
My issue is solved after I changed double quote `"` to single quote `'` around plugin names.

**Comment by nscott32** [comment]
Thanks but as you can see I use single quote in my vimrc.

**Comment by Fandekasp** [comment]
I got the same issue, and the reason was that I had installed the package "vundle" from aur, which is outdated. Removing it then installing "aur/vundle-git" fixed the issue.

**Comment by nonemaw** [comment]
I have the same error when I open python files under zsh via vim, and I fixed it after I update the "vim" alias in .zshrc (I changed the vim directory, therefore "vim" alias is used under .bashrc, and I forgot writing it into .zshrc)

**Comment by itsamoreh** [comment]
Thank you @Fandekasp that fixed it for me!

**Comment by ryanoasis** [comment]
@nscott32 still having this issue?

**Comment by klas-genestack** [comment]
I'm still having this issue on MacOS X with up-to-date Vundle repo.

The only thing that comes to mind about what could cause something like this is that I have NeoVim installed as well, and they use the same config and vundle dirs.

**Comment by pmalek** [comment]
I am still having this issue on Ubuntu 14.04 with zsh and all plugins listed with single quotes in `~/.vimrc` and with properly set

    set rtp+=~/.vim/bundle/Vundle.vim

**Comment by nfischer** [comment]
@pmalek Please post or link to your vimrc, otherwise we won't be able to help you. From what you've described, it sounds like everything is ok so far.

**Comment by pmalek** [comment]
@nfischer Sure thing. Although now (after update or some magical intervention) the error went away.

**Comment by barnaba** [comment]
Had a same error in fish 2.2.0, setting `shell=/bin/bash` fixed it on ubuntu 14.04

**Comment by michft** [comment]
Might be spf13 specific.

https://github.com/spf13/spf13-vim/issues/738

**Comment by Dorian** [comment]
Using the fish shell here, adding `set shell=/bin/bash` to my `.vimrc` fixed it

**Comment by ryanoasis** [comment]
Closing for now. _Seems_ like everyone with issues posted here have come to their own solutions. Please let it be known if otherwise.

**Comment by vikeri** [comment]
The overwhelming amount of 👍  for @Dorian's answer makes me think that that should be added to the install README as a not for fish shell users.

**Comment by ryanoasis** [comment]
I will attempt to fast-track some of these issue tomorrow. Thanks everyone

**Comment by oswinfox** [comment]
for me :set bash=/bin/bash solved the issue

**Comment by pablojaviersosa** [comment]
> for me :set bash=/bin/bash solved the issue
 :set shell=/bin/bash 
Esto me solucionó el problema, o lo que es lo mismo
set shell=/bin/bash en ~/.vimrc
Saludos

**Comment by shikari7** [comment]
I had this error and was able to get this to work.  First I added the set shell=/bin/bash and that did not help.
I then removed the " comments (and trailing blank space) and then no errors and :BundleInstall worked.

**Comment by meanbunny** [comment]
> I got the same issue, and the reason was that I had installed the package "vundle" from aur, which is outdated. Removing it then installing "aur/vundle-git" fixed the issue.

Thank you!

**Comment by fsultani** [comment]
The problem for me was in my vimrc.  I had a customization setting for the preview popup:
```
set previewpopup=height:50,width:150
```

This was somehow conflicting with [ack](https://github.com/mileszs/ack.vim).  By commenting it out, I was able to install the plugin.
